name: pytest
on: [ "push", "pull_request"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update branch protection
          uses: Hatzelencio/branch-protection@v1.0.0
          env:
            GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        - name: Set up Python 3.
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: lint with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Test with pytest
          run: |
            pytest test
        - name: docker builde
          run: |
            docker build .